# Generated by Django 3.0.7 on 2020-06-22 01:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='stream',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
    ]
