# Generated by Django 3.0.7 on 2020-06-22 01:50

from django.db import migrations, models
import django.db.models.deletion
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0005_homepage_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='stream',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('recipe', wagtail.snippets.blocks.SnippetChooserBlock(home.models.Recipe))], blank=True),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients', wagtail.core.fields.StreamField([('ingredient', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('quantity', wagtail.core.blocks.DecimalBlock()), ('unit', wagtail.core.blocks.ChoiceBlock(choices=[('none', '(no unit)'), ('g', 'Grams (g)'), ('ml', 'Millilitre (ml)'), ('tsp', 'Teaspoon (tsp.)'), ('tbsp', 'Tablespoon (tbsp.)')]))]))])),
                ('instructions', wagtail.core.fields.StreamField([('instruction', wagtail.core.blocks.TextBlock())])),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
